version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: P4ssw0rd!
      MONGO_INITDB_DATABASE: tac_grupo_4
    volumes:
      - mongodb-data:/data/db
    networks:
      - my-network

  grupo_4:
    build:
      context: .
    container_name: grupo_4
    ports:
      - "8080:8080"
    environment:
      #Ojo que sobreescribe el application.yaml
      - SPRING_DATA_MONGODB_URI=mongodb://root:P4ssw0rd!@mongodb:27017/tac_grupo_4?authSource=admin
      - CORRIENDO_EN_DOCKER=true
    networks:
      - my-network
    depends_on:
      - mongodb
networks:
  my-network:
    driver: bridge

volumes:
  mongodb-data:
