server:
  port: 8080
spring:
  application:
    name: grupo-4
  data:
    mongodb:
      authentication-database: admin
      database: tac-grupo-4
      additional-hosts: localhost
      username: root
      password: P4ssw0rd!

telegram:
  bot:
    token: 6042310161:AAGVgUKPJmFckdOGgVi6O4mZUS1hWYI8u8k