server:
  port: 8080
spring:
  application:
    name: grupo-4
  datasource:
    url: jdbc:mysql://localhost/tac-grupo-4
    username: root
    password: P4ssw0rd!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL8Dialect
