server:
  port: 8080
spring:
  application:
    name: grupo-4
  data:
    mongodb:
      authentication-database: admin
      database: tac-grupo-4
      additional-hosts: localhost
      username: root
      password: P4ssw0rd!

