server:
  port: 8080
spring:
  application:
    name: grupo-4
  data:
    mongodb:
      authentication-database: admin
      database: tac-grupo-4
      additional-hosts: localhost
      username: root
      password: P4ssw0rd!
      auto-index-creation: true

telegram:
  bot:
    token: TOKEN-VA-ACA

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
              index:
                MongoPersistentEntityIndexCreator: DEBUG
